import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  learnToolsSidebar: [
    {
      type: 'category',
      label: 'Why Ballerina',
      collapsed: true,
      collapsible: true,
      items: [
        {type: 'link', label: 'Cloud native', href: '/learn/why-ballerina/cloud-native/'},
        {type: 'link', label: 'Flexibly typed', href: '/learn/why-ballerina/flexibly-typed/'},
        {type: 'link', label: 'Data oriented', href: '/learn/why-ballerina/data-oriented/'},
        {type: 'link', label: 'Graphical', href: '/learn/why-ballerina/graphical/'},
        {type: 'link', label: 'Concurrent', href: '/learn/why-ballerina/concurrent/'},
        {type: 'link', label: 'Reliable, maintainable', href: '/learn/why-ballerina/reliable-maintainable/'},
      ],
    },
    {
      type: 'category',
      label: 'Get started with integration',
      collapsed: true,
      collapsible: true,
      items: [
        'integration/get-started',
        'install-ballerina/installation-options',
        {type: 'link', label: 'Pre-built integrations', href: '/learn/pre-built-integrations/'},
        {type: 'link', label: 'Enterprise Integration Patterns (EIP)', href: '/learn/enterprise-integration-patterns/'},
        {type: 'link', label: 'Integration tutorials', href: '/learn/integration/integration-tutorials/'},
        {type: 'link', label: 'Supported data formats', href: '/learn/supported-data-formats/'},
        {type: 'link', label: 'Supported network integration protocols', href: '/learn/supported-network-protocols/'},
      ],
    },
    {
      type: 'category',
      label: 'Integration tools',
      link: {type: 'doc', id: 'integration-tools/intro'},
      collapsed: true,
      collapsible: true,
      items: [
        'integration-tools/openapi-tool',
        'integration-tools/graphql-tool',
        'integration-tools/asyncapi-tool',
        'integration-tools/grpc-tool',
        'integration-tools/health-tool',
        'integration-tools/edi-tool',
        'integration-tools/wsdl-tool',
        'integration-tools/xsd-tool',
      ],
    },
    {
      type: 'category',
      label: 'References',
      collapsed: true,
      collapsible: true,
      items: [
        {type: 'link', label: 'Ballerina by Example', href: '/learn/by-example/'},
        {type: 'link', label: 'Ballerina API Docs', href: 'https://lib.ballerina.io/'},
        'references/ballerina-specifications',
        {
          type: 'category',
          label: 'Visual Studio Code extension',
          collapsed: true,
          collapsible: true,
          items: [
            {type: 'link', label: 'Overview', href: '/learn/vs-code-extension/'},
            'vs-code-extension/get-started',
            'vs-code-extension/configure-the-extension',
            'vs-code-extension/build-executables',
            'vs-code-extension/notebooks',
            'vs-code-extension/run-a-program',
            'vs-code-extension/test-the-code',
            {
              type: 'category',
              label: 'Write the code',
              collapsed: true,
              collapsible: true,
              items: [
                'vs-code-extension/write-the-code/intellisense',
                'vs-code-extension/write-the-code/code-actions',
                'vs-code-extension/write-the-code/code-navigation',
                'vs-code-extension/write-the-code/diagnostics',
                'vs-code-extension/write-the-code/commands',
              ],
            },
            {
              type: 'category',
              label: 'Debug the code',
              collapsed: true,
              collapsible: true,
              items: [
                'vs-code-extension/debug-the-code/debug-configurations',
                'vs-code-extension/debug-the-code/debug-features',
                'vs-code-extension/debug-the-code/debug-sessions',
              ],
            },
            {
              type: 'category',
              label: 'Design the services',
              collapsed: true,
              collapsible: true,
              items: [
                'vs-code-extension/design-the-services/http-api-designer',
                'vs-code-extension/design-the-services/graphql-api-designer',
              ],
            },
            {
              type: 'category',
              label: 'Try the services',
              collapsed: true,
              collapsible: true,
              items: [
                'vs-code-extension/try-the-services/try-http-services',
                'vs-code-extension/try-the-services/try-graphql-services',
              ],
            },
            {
              type: 'category',
              label: 'Implement the code',
              collapsed: true,
              collapsible: true,
              items: [
                'vs-code-extension/implement-the-code/ballerina-visualizer-view',
                'vs-code-extension/implement-the-code/data-mapper',
                'vs-code-extension/implement-the-code/entity-relationship-diagram-view',
              ],
            },
            {
              type: 'category',
              label: 'References',
              collapsed: true,
              collapsible: true,
              items: [
                'vs-code-extension/references/convert-json-to-records',
                'vs-code-extension/references/record-editor',
              ],
            },
            {
              type: 'category',
              label: 'Release notes',
              collapsed: true,
              collapsible: true,
              items: [
                'vs-code-extension/release-notes/version-4.5.0',
                'vs-code-extension/release-notes/version-4.4.0',
                'vs-code-extension/release-notes/version-4.3.0',
                'vs-code-extension/release-notes/version-4.0.0',
                'vs-code-extension/release-notes/version-3.3.0',
              ],
            },
            'vs-code-extension/troubleshoot',
            'vs-code-extension/license',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Development tutorials',
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: 'category',
          label: 'Build and run',
          collapsed: true,
          collapsible: true,
          items: [
            'development-tutorials/build-and-run/cli-commands',
            'development-tutorials/build-and-run/update-tool',
            'development-tutorials/build-and-run/ballerina-shell',
            'development-tutorials/build-and-run/cicd',
          ],
        },
        {
          type: 'category',
          label: 'Source code & dependencies',
          collapsed: true,
          collapsible: true,
          items: [
            'development-tutorials/source-code-dependencies/organize-ballerina-code',
            'development-tutorials/source-code-dependencies/package-references',
            'development-tutorials/source-code-dependencies/manage-dependencies',
            'development-tutorials/source-code-dependencies/workspaces',
          ],
        },
        {
          type: 'category',
          label: 'Style guide',
          collapsed: true,
          collapsible: true,
          items: [
            'development-tutorials/source-code-dependencies/style-guide/coding-conventions',
            'development-tutorials/source-code-dependencies/style-guide/top-level-definitions',
            'development-tutorials/source-code-dependencies/style-guide/operators-keywords-and-types',
            'development-tutorials/source-code-dependencies/style-guide/statements',
            'development-tutorials/source-code-dependencies/style-guide/expressions',
            'development-tutorials/source-code-dependencies/style-guide/annotations-documentation-and-comments',
            'development-tutorials/source-code-dependencies/style-guide/customize-formatting',
          ],
        },
        {
          type: 'category',
          label: 'Test, debug & document the code',
          collapsed: true,
          collapsible: true,
          items: [
            {
              type: 'category',
              label: 'Test Ballerina code',
              collapsed: true,
              collapsible: true,
              items: [
                'development-tutorials/test-document-the-code/test-ballerina-code/test-a-simple-function',
                'development-tutorials/test-document-the-code/test-ballerina-code/write-tests',
                'development-tutorials/test-document-the-code/test-ballerina-code/structure-tests',
                'development-tutorials/test-document-the-code/test-ballerina-code/configure-tests',
                'development-tutorials/test-document-the-code/test-ballerina-code/code-coverage-and-reporting',
                'development-tutorials/test-document-the-code/test-ballerina-code/define-data-driven-tests',
                'development-tutorials/test-document-the-code/test-ballerina-code/define-test-groups',
                'development-tutorials/test-document-the-code/test-ballerina-code/test-services-and-clients',
                'development-tutorials/test-document-the-code/test-ballerina-code/mocking',
                'development-tutorials/test-document-the-code/test-ballerina-code/execute-tests',
                'development-tutorials/test-document-the-code/test-ballerina-code/execute-tests-in-parallel',
              ],
            },
            'development-tutorials/test-document-the-code/debug-ballerina-programs',
            'development-tutorials/test-document-the-code/generate-code-documentation',
          ],
        },
        {
          type: 'category',
          label: 'Configurability',
          collapsed: true,
          collapsible: true,
          items: [
            'development-tutorials/configurability/configure-a-sample-ballerina-service',
            'development-tutorials/configurability/provide-values-to-configurable-variables',
            'development-tutorials/configurability/configure-values',
          ],
        },
        {
          type: 'category',
          label: 'Deployment guidelines',
          collapsed: true,
          collapsible: true,
          items: [
            'development-tutorials/deployment-guide/deployment-guidelines-overview',
            'development-tutorials/deployment-guide/monolithic-deployment',
            'development-tutorials/deployment-guide/containerized-deployment',
            'development-tutorials/deployment-guide/serverless-deployment',
            'development-tutorials/deployment-guide/keystore-truststore',
          ],
        },
        {
          type: 'category',
          label: 'Bal persist',
          collapsed: true,
          collapsible: true,
          items: [
            'development-tutorials/ballerina-persist/bal-persist-overview',
            'development-tutorials/ballerina-persist/persist-model',
            'development-tutorials/ballerina-persist/persist-cli-tool',
            'development-tutorials/ballerina-persist/persist-client-api',
            'development-tutorials/ballerina-persist/persist-introspection',
            'development-tutorials/ballerina-persist/supported-data-stores',
          ],
        },
        {
          type: 'category',
          label: 'Observability',
          collapsed: true,
          collapsible: true,
          items: [
            'development-tutorials/observability/overview-of-ballerina-observability',
            {
              type: 'category',
              label: 'Supported observability tools and platforms',
              collapsed: true,
              collapsible: true,
              items: [
                'development-tutorials/observability/supported-observability-tools-and-platforms/prometheus',
                'development-tutorials/observability/supported-observability-tools-and-platforms/jaeger',
                'development-tutorials/observability/supported-observability-tools-and-platforms/zipkin',
                'development-tutorials/observability/supported-observability-tools-and-platforms/datadog',
                'development-tutorials/observability/supported-observability-tools-and-platforms/new-relic',
                'development-tutorials/observability/supported-observability-tools-and-platforms/elastic-stack',
                'development-tutorials/observability/supported-observability-tools-and-platforms/opensearch',
                'development-tutorials/observability/supported-observability-tools-and-platforms/moesif',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Java interoperability',
          collapsed: true,
          collapsible: true,
          items: [
            'development-tutorials/java-interoperability/call-java-code-from-ballerina',
            'development-tutorials/java-interoperability/ballerina-ffi',
            'development-tutorials/java-interoperability/the-bindgen-tool',
          ],
        },
        {
          type: 'category',
          label: 'Build a GraalVM executable',
          collapsed: true,
          collapsible: true,
          items: [
            'development-tutorials/build-a-graalvm-executable/graalvm-executable-overview',
            'development-tutorials/build-a-graalvm-executable/build-the-executable-in-a-container',
            'development-tutorials/build-a-graalvm-executable/build-the-executable-locally',
          ],
        },
        {
          type: 'category',
          label: 'Reuse code with Ballerina Central',
          collapsed: true,
          collapsible: true,
          items: [
            'development-tutorials/ballerina-central/publish-packages-to-ballerina-central',
            'development-tutorials/ballerina-central/configure-a-network-proxy',
            'development-tutorials/ballerina-central/proxy-ballerina-central-with-maven-repository',
          ],
        },
        {
          type: 'category',
          label: 'Run in the cloud',
          collapsed: true,
          collapsible: true,
          items: [
            'development-tutorials/run-in-the-cloud/code-to-cloud-deployment',
          ],
        },
        {
          type: 'category',
          label: 'Troubleshoot the runtime',
          collapsed: true,
          collapsible: true,
          items: [
            'development-tutorials/troubleshoot-the-runtime/strand-dump-tool',
            'development-tutorials/troubleshoot-the-runtime/ballerina-profiler',
          ],
        },
        {
          type: 'category',
          label: 'Static code analysis',
          collapsed: true,
          collapsible: true,
          items: [
            'development-tutorials/static-code-analysis/scan-tool',
            'development-tutorials/static-code-analysis/scan-rules',
          ],
        },
        {
          type: 'category',
          label: 'Additional tools',
          collapsed: true,
          collapsible: true,
          items: [
            'development-tutorials/additional-tools/consolidate-packages-tool',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: 'category',
          label: 'Featured scenarios',
          collapsed: true,
          collapsible: true,
          items: [
            'resources/featured-scenarios/write-a-restful-api-with-ballerina',
            'resources/featured-scenarios/write-a-grpc-service-with-ballerina',
            'resources/featured-scenarios/write-a-graphql-api-with-ballerina',
            'resources/featured-scenarios/work-with-data-using-queries-in-ballerina',
            'resources/featured-scenarios/build-a-data-service-in-ballerina',
            'resources/featured-scenarios/build-a-change-data-capture-service-in-ballerina',
            'resources/featured-scenarios/work-with-llms-using-natural-expressions',
            'resources/featured-scenarios/deploy-ballerina-on-kubernetes',
            'resources/featured-scenarios/manage-data-persistence-with-bal-persist',
            'resources/featured-scenarios/create-your-first-connector-with-ballerina',
          ],
        },
        {
          type: 'category',
          label: 'Learn the language',
          collapsed: true,
          collapsible: true,
          items: [
            'resources/learn-the-language/language-basics',
            'resources/learn-the-language/network-interaction',
            'resources/learn-the-language/data',
            'resources/learn-the-language/concurrency',
            'resources/learn-the-language/advanced-general-purpose-language-features',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
